name: scrape-and-index
on:
  schedule:
    - cron: "23 5 7 * *"   # 05:23 UTC on the 7th each month
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crawl + index links (no OCR yet)
        run: python tbc_scraper.py

      - name: Summarize run
        run: |
          python - <<'PY'
          import os, pandas as pd
          from pathlib import Path
          p = Path("data/derived/sources_index.csv")
          if p.exists():
            df = pd.read_csv(p)
            rows = len(df)
            earliest = df['report_date'].min() if 'report_date' in df else 'NA'
            latest   = df['report_date'].max() if 'report_date' in df else 'NA'
          else:
            rows, earliest, latest = 0, 'NA', 'NA'
          summ = Path(os.environ["GITHUB_STEP_SUMMARY"])
          summ.write_text(
            f"# Step 1 summary\n"
            f"- rows: {rows}\n"
            f"- earliest: {earliest}\n"
            f"- latest: {latest}\n"
          )
          PY

      - name: Commit index CSV
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/derived/sources_index.csv README.md
          git commit -m "update: Step 1 link index" || echo "no changes"
          git push
